export const STACKS = [
  {
    id: 'nextjs',
    name: 'Next.js',
    logo: 'nextjs',
    tint: '#000000',
    summary: 'React framework with SSR and app router',
    detect: ['next'],
    clusterable: true,
    defaults: {
      build: 'npm run build',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      port: 3000,
      env: 'NODE_ENV=production',
      execMode: 'fork',
    },
  },
  {
    id: 'sveltekit',
    name: 'SvelteKit',
    logo: 'sveltekit',
    tint: '#FF3E00',
    summary: 'Svelte framework, adapter-node build',
    detect: ['@sveltejs/kit'],
    clusterable: true,
    defaults: {
      build: 'npm run build',
      script: 'build/index.js',
      args: '',
      port: 3000,
      env: 'NODE_ENV=production',
      execMode: 'fork',
    },
  },
  {
    id: 'express',
    name: 'Express',
    logo: 'express',
    tint: '#000000',
    summary: 'Minimal Node.js web server',
    detect: ['express'],
    clusterable: true,
    defaults: { build: '', script: 'server.js', args: '', port: 3000, env: 'NODE_ENV=production', execMode: 'cluster' },
  },
  {
    id: 'fastify',
    name: 'Fastify',
    logo: 'fastify',
    tint: '#000000',
    summary: 'Fast, low-overhead Node.js server',
    detect: ['fastify'],
    clusterable: true,
    defaults: { build: '', script: 'server.js', args: '', port: 3000, env: 'NODE_ENV=production', execMode: 'cluster' },
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    logo: 'nestjs',
    tint: '#E0234E',
    summary: 'Structured TypeScript backend framework',
    detect: ['@nestjs/core'],
    clusterable: true,
    defaults: {
      build: 'npm run build',
      script: 'dist/main.js',
      args: '',
      port: 3000,
      env: 'NODE_ENV=production',
      execMode: 'cluster',
    },
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    logo: 'nuxt',
    tint: '#00DC82',
    summary: 'Vue framework with SSR',
    detect: ['nuxt'],
    clusterable: true,
    defaults: {
      build: 'npm run build',
      script: '.output/server/index.mjs',
      args: '',
      port: 3000,
      env: 'NODE_ENV=production',
      execMode: 'fork',
    },
  },
  {
    id: 'astro',
    name: 'Astro',
    logo: 'astro',
    tint: '#BC52EE',
    summary: 'Content site, node adapter',
    detect: ['astro'],
    clusterable: true,
    defaults: {
      build: 'npm run build',
      script: 'dist/server/entry.mjs',
      args: '',
      port: 4321,
      env: 'HOST=0.0.0.0',
      execMode: 'fork',
    },
  },
  {
    id: 'vite',
    name: 'Vite / SPA',
    logo: 'vite',
    tint: '#646CFF',
    summary: 'Static build served by PM2',
    detect: ['vite'],
    clusterable: false,
    serve: { dir: 'dist', spa: true },
    defaults: { build: 'npm run build', script: '', args: '', port: 5000, env: '', execMode: 'fork' },
  },
  {
    id: 'react',
    name: 'React',
    logo: 'react',
    tint: '#61DAFB',
    summary: 'Static build served by PM2',
    detect: ['react-scripts'],
    clusterable: false,
    serve: { dir: 'build', spa: true },
    defaults: { build: 'npm run build', script: '', args: '', port: 5000, env: '', execMode: 'fork' },
  },
  {
    id: 'node',
    name: 'Node.js',
    logo: 'node',
    tint: '#5FA04E',
    summary: 'Any plain Node script or worker',
    detect: [],
    clusterable: true,
    defaults: { build: '', script: 'index.js', args: '', port: null, env: '', execMode: 'fork' },
  },
  {
    id: 'python',
    name: 'Python',
    logo: 'python',
    tint: '#3776AB',
    summary: 'FastAPI, Flask or Django via interpreter',
    detect: [],
    clusterable: false,
    defaults: {
      build: '',
      script: 'main.py',
      args: '',
      port: 8000,
      env: '',
      execMode: 'fork',
      interpreter: 'python3',
    },
  },
  {
    id: 'go',
    name: 'Go',
    logo: 'go',
    tint: '#00ADD8',
    summary: 'Compiled binary supervised by PM2',
    detect: [],
    clusterable: false,
    defaults: {
      build: 'go build -o app .',
      script: './app',
      args: '',
      port: 8080,
      env: '',
      execMode: 'fork',
      interpreter: 'none',
    },
  },
];

export const STACK_BY_ID = Object.fromEntries(STACKS.map((s) => [s.id, s]));

export function detectStack(pkg) {
  if (!pkg) return null;
  const deps = new Set([...(pkg.dependencies ?? []), ...(pkg.devDependencies ?? []), ...(pkg.allDeps ?? [])]);
  for (const stack of STACKS) {
    if (stack.detect.some((d) => deps.has(d))) return stack.id;
  }
  return null;
}
